### PR TITLE
Feature/editor styles to match front end

### LINKED ISSUE #39: Updates for editor styling to match their front end appearance.
By default blocks are rather narrow on screen while editing on the backend. These styles will more closely reflect how they'll be output on the front end.

### PR DESCRIPTION
**Pull request by ImBigWill**
Closes #39

### LINK ###
No specific link, can be tested just creating a page with our blocks to verify/test/view

### DESCRIPTION ###
- I think this is in a good spot and is ready for review/code merge. There are some styles for blocks for the admin area so they're more in line with how they'll look on the front end. I think the one block that's not just yet is related posts and I think that might be happening in conjunction with the work on that branch or we can adjust as need be down the line. This is more of just an up to date with the current blocks and their states. 
- Some other notes, blocks with options are typically full width. 
- Styles amongst blocks are more consistent. 
- A bit of breathing room between blocks for a nicer experience. By default they sort of stack and even almost overlap sometimes.
- The active/focused/hovered blocks get full opacity and the others on the page are lighter when they're not the current block being edited/viewed. 
- For more global styling I created a sass folder, which contains breakpoints, variables, mixins and some global styles that were originally in common.scss, which now just imports the partials in the sass folder.

### SCREENSHOTS ###
[Screenshot](https://www.dropbox.com/s/0k0x5gi2xnrn2so/Screenshot%202018-04-16%2010.08.41.png?dl=0)

### OTHER ###
- [x] Is this issue accessible? (Section 508/WCAG 2.0AA)
- [x] Does this issue pass all the linting? (PHPCS, ESLint, SassLint)
- [x] Does this pass CBT?

### FILES ###
- https://github.com/WebDevStudios/wds-gutenberg/tree/feature/editor-styles-to-match-front-end/src/sass
- https://github.com/WebDevStudios/wds-gutenberg/tree/feature/editor-styles-to-match-front-end/src/blocks (editor.scss files and styles.scss files for each block)

### STEPS TO VERIFY ###
I think the best way to test this is checkout the branch and view a page in the admin with our blocks setup. 

### DOCUMENTATION ###
This is mostly if not all just appearance and does not require any additional extra steps.

### CODE REVIEW

**Comment by coreymcollins** [comment]
I think this is looking mostly good, though I am experiencing a visual thing in the dashboard we could probably adjust.  I know the idea came up before about "dimming" the inactive blocks to make it more obvious which block you were in/editing, but if I have no block selected all of the blocks are dimmed:


If we're going to dim the inactive blocks, we should only do so when another block is active otherwise we get the weird, washed-out look on every block on the page.

--------

Are we able to move some of the individual styles from single block `editor.scss` files to the `_block-blocks.scss` file?  For instance, styles like `.has-custom-background`, `.has-video-background`, and setting `max-width: none`?  It seems like we could target everything all in one swoop in `_global-blocks`, but maybe there's a hiccup there I'm not thinking of.

--------

Overall I think these are looking much better being full-width (or as full-width as they can be with allowing for the left & right space for Gutenberg functionality) than they were being cramped in the center of the screen before.  One last thing I'm thinking about is the rendering of buttons in the Hero and CTA blocks in the dashboard, and if we should utilize the same type of thing we're doing for Related Posts by rendering the actual link markup when we focus off of the block.  I don't think it's a necessity and could be a quick and easy Phase II task, so I would confirm whether or not we should tackle that here or not with @gregrickaby before moving on it.

**Comment by coreymcollins** [comment]
Also, as noted by @ImBigWill the Related Posts block is absent from this branch as it is in an active PR at #41. I think getting this PR merged in first will help with styling there, because we should be able to adopt a decent amount of global styles for Related Posts in the dashboard rather than having @jomurgel style something, then have to potentially rework it once Will's work here is merged in.

**Comment by gregrickaby** [comment]
I'm coming at this with _very_ fresh eyes. I have been absent from this project for a few weeks. Here are a few QA/UX things...

# Hero block
- Very tall when inserted.
- There's also no indication that I can add paragraph text.

screenshot

# Two-Column block 
- Having the column titles same size/color as the block title, was confusing. I thought they were editable.
screenshot
- Here is an in-browser mock-up of what I think the Two-Column block UX could be:
screenshot

# Call To Action Block
- There's nothing indicating that I can add paragraph text. It wasn't until I accidentally clicked into that area, that I realized I could change it. Instead of "click advanced options..." maybe it could read "Click to add paragraph text". 
screenshot

**Comment by ImBigWill** [comment]
I made the requested updates best I could here. I trimmed the height of the hero to about half the size, I thought the original size there was intentional initially. Placeholder text is displaying and editable with some update verbiage added. The two column block isn't currently setup for editable titles to change on the fly so in chatting with Corey tried to combine the notes above with how it's currently setup. And then lastly adjusted the text of the cta block as well.

### Commits: ###
https://github.com/WebDevStudios/wds-gutenberg/commit/1c8328fdf19d1e28f0424c197d1d987ef61385d0
https://github.com/WebDevStudios/wds-gutenberg/commit/f3e656de4e1004ebe200406af32071bbd9e970bd

### SCREENSHOTS ###
Hero
Two-Column
CTA

**Pull request merged**
